USE Company_SD;

-- 1 --
select * from EMPLOYEE

-- 2 --
SELECT FNAME,LNAME,SALARY,DNO FROM EMPLOYEE

-- 3 ---
SELECT PNAME,PLOCATION,DNUM FROM PROJECT

---4---
SELECT 
  CONCAT(FNAME, ' ', LNAME) AS FULL_NAME,
  (SALARY * 12 * 0.10) AS ANNUAL_COMM
FROM EMPLOYEE;

-- 5 --
SELECT SSN, CONCAT(FNAME, ' ', LNAME) AS FULL_NAME
FROM EMPLOYEE
WHERE SALARY > 1000;
 
-- 6 --
SELECT SSN, CONCAT(FNAME, ' ', LNAME) AS FULL_NAME
FROM EMPLOYEE
WHERE SALARY * 12 > 10000;

-- 7 --
SELECT FNAME, LNAME, SALARY 
FROM EMPLOYEE
WHERE SEX = 'F';

-- 8 --
SELECT DNUMBER, DNAME 
FROM DEPARTMENT
WHERE MGRSSN = '987654321';

-- 9 --
SELECT PNUMBER, PNAME, PLOCATION 
FROM PROJECT
WHERE DNUM = 10;


