-- 1 --
SELECT D.DNUMBER, D.DNAME, E.SSN AS ManagerID, E.Fname + ' ' + E.Lname AS ManagerName
FROM DEPARTMENT D
JOIN EMPLOYEE E ON D.MGRSSN = E.SSN;

-- 2 --
SELECT D.DNAME, P.PNAME
FROM DEPARTMENT D
JOIN PROJECT P ON D.DNUMBER = P.DNUM;

-- 3  --
SELECT DEP.*, E.Fname + ' ' + E.Lname AS EmployeeName
FROM DEPENDENT DEP
JOIN EMPLOYEE E ON DEP.ESSN = E.SSN;

-- 4 --
SELECT PNUMBER, PNAME, PLOCATION
FROM PROJECT
WHERE PLOCATION IN ('Cairo', 'Alex');

-- 5 --
SELECT *
FROM PROJECT
WHERE PNAME LIKE 'A%';

-- 6 --
SELECT *
FROM EMPLOYEE
WHERE DNO = 30 AND SALARY BETWEEN 1000 AND 2000;

-- 7 --
SELECT E.Fname + ' ' + E.Lname AS EmployeeName
FROM EMPLOYEE E
JOIN WORKS_FOR W ON E.SSN = W.ESSN
JOIN PROJECT P ON W.PNO = P.PNUMBER
WHERE E.DNO = 10 AND W.HOURS >= 10 AND P.PNAME = 'AL Rabwah';

-- 8 --
SELECT E2.Fname + ' ' + E2.Lname AS EmployeeName
FROM EMPLOYEE E1
JOIN EMPLOYEE E2 ON E1.SSN = E2.SUPERSSN
WHERE E1.Fname = 'Kamel' AND E1.Lname = 'Mohamed';

-- 9 --
SELECT E.Fname + ' ' + E.Lname AS EmployeeName, P.PNAME
FROM EMPLOYEE E
JOIN WORKS_FOR W ON E.SSN = W.ESSN
JOIN PROJECT P ON W.PNO = P.PNUMBER
ORDER BY P.PNAME;

-- 10 --
SELECT P.PNUMBER, D.DNAME, M.Lname AS ManagerLastName, M.Address, M.BDATE
FROM PROJECT P
JOIN DEPARTMENT D ON P.DNUM = D.DNUMBER
JOIN EMPLOYEE M ON D.MGRSSN = M.SSN
WHERE P.PLOCATION = 'Cairo';

-- 11 --
SELECT *
FROM EMPLOYEE
WHERE SSN IN (SELECT MGRSSN FROM DEPARTMENT);

-- 12 --
SELECT E.*, D.Dependent_name, D.Sex, D.Bdate
FROM EMPLOYEE E
LEFT JOIN DEPENDENT D ON E.SSN = D.ESSN;


-------------------------------------------------
---- DML ----
INSERT INTO EMPLOYEE (SSN, FNAME, LNAME, SALARY, SUPERSSN, DNO)
VALUES (102672, 'Farah', 'Ahmed', 3000, 112233, 30);


INSERT INTO EMPLOYEE (SSN, FNAME, LNAME, DNO)
VALUES (102660, 'Nour', 'Wael', 30);


UPDATE EMPLOYEE
SET SALARY = SALARY * 1.2
WHERE SSN = 102672;
